# Generated by Django 5.2 on 2025-07-12 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_skills'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentinspection',
            options={'ordering': ['organisation', '-inspection_date'], 'verbose_name': 'Component Inspection', 'verbose_name_plural': 'Component Inspections'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['organisation', '-date'], 'verbose_name': 'Maintenance Record', 'verbose_name_plural': 'Maintenance Records'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['organisation', '-created_at'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehiclechangelog',
            options={'ordering': ['organisation', '-created_at'], 'verbose_name': 'Vehicle Change Log', 'verbose_name_plural': 'Vehicle Change Logs'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecomponent',
            options={'ordering': ['organisation', 'category', 'name'], 'verbose_name': 'Vehicle Component', 'verbose_name_plural': 'Vehicle Components'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecomponentinstance',
            options={'ordering': ['organisation', '-created_at'], 'verbose_name': 'Vehicle Component Instance', 'verbose_name_plural': 'Vehicle Component Instances'},
        ),
        migrations.AlterModelOptions(
            name='vehicledocument',
            options={'ordering': ['organisation', '-created_at'], 'verbose_name': 'Vehicle Document', 'verbose_name_plural': 'Vehicle Documents'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemake',
            options={'ordering': ['organisation', 'name'], 'verbose_name': 'Vehicle Make', 'verbose_name_plural': 'Vehicle Makes'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['organisation', 'make__name', 'name'], 'verbose_name': 'Vehicle Model', 'verbose_name_plural': 'Vehicle Models'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['organisation', 'name'], 'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecomponent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='componentinspection',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='component_inspections', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclechangelog',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_change_logs', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclecomponent',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_components', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclecomponentinstance',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_component_instances', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documents', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemake',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_makes', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='core.organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='License plate can only contain letters, numbers, hyphens, and spaces', regex='^[A-Z0-9\\-\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('van', 'Van'), ('suv', 'SUV'), ('bicycle', 'Bicycle'), ('scooter', 'Scooter'), ('trailer', 'Trailer'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('organisation', 'license_plate')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecomponent',
            unique_together={('organisation', 'name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemake',
            unique_together={('organisation', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('organisation', 'make', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicletype',
            unique_together={('organisation', 'name')},
        ),
    ]
