# Generated by Django 5.2 on 2025-07-21 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('service_management', '0013_remove_spacesettings_enable_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='space',
            field=models.ForeignKey(blank=True, help_text='Space where this transaction was recorded', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='service_management.spaces'),
        ),
    ]
