# Generated by Django 5.2 on 2025-07-22 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialtransaction_space'),
        ('service_management', '0013_remove_spacesettings_enable_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='space',
            field=models.ForeignKey(blank=True, help_text='Space where this budget applies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='service_management.spaces'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='space',
            field=models.ForeignKey(blank=True, help_text='Space where this recurring transaction applies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='service_management.spaces'),
        ),
    ]
