# Generated by Django 5.2 on 2025-06-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_org'),
        ('service_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_categories', to='core.organisation'),
            preserve_default=False,
        ),
    ]
