# Generated by Django 5.2 on 2025-07-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0004_shoppingliststatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='shoppingliststatushistory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
