# Generated by Django 5.2 on 2025-07-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0005_purchaseitem_slug_shoppinglistitem_slug_and_more'),
    ]

    operations = [
    ]
