# Generated by Django 5.2 on 2025-07-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0006_auto_20250707_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('purchase_created', 'Purchase Order Created')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppingliststatushistory',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('purchase_created', 'Purchase Order Created')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppingliststatushistory',
            name='old_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('purchase_created', 'Purchase Order Created')], max_length=20),
        ),
    ]
