# Generated by Django 5.2 on 2025-07-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0007_alter_shoppinglist_status_and_more'),
    ]

    operations = [
    ]
