# Generated by Django 5.2 on 2025-07-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0009_spaces_spacesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacesettings',
            name='auto_assign_maintainers',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='enable_issue_attachments',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='enable_issue_comments',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='enable_service_purchases',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='enable_service_requests',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='enable_service_upgrades',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='enable_transport_booking',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='in_app_notifications',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='max_advance_booking_days',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='require_issue_approval',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='require_transport_approval',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='sms_notifications',
        ),
    ]
