# Generated by Django 5.2 on 2025-07-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0010_remove_spacesettings_auto_assign_maintainers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='shopping_list_item',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='org',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='shopping_list',
        ),
        migrations.RemoveField(
            model_name='shoppingliststatushistory',
            name='shopping_list',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shoppingliststatushistory',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
        migrations.DeleteModel(
            name='ShoppingListStatusHistory',
        ),
    ]
