# Generated by Django 5.2 on 2025-07-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0011_remove_purchaseitem_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacesettings',
            name='enable_asset_management',
            field=models.BooleanField(default=False, help_text='Enable/disable asset management'),
        ),
        migrations.AddField(
            model_name='spacesettings',
            name='enable_finance',
            field=models.BooleanField(default=True, help_text='Enable/disable finance management'),
        ),
        migrations.AddField(
            model_name='spacesettings',
            name='enable_marketplace',
            field=models.BooleanField(default=True, help_text='Enable/disable marketplace'),
        ),
    ]
