# Generated by Django 5.2 on 2025-07-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0012_spacesettings_enable_asset_management_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacesettings',
            name='enable_dashboard',
        ),
    ]
