# Generated by Django 5.2 on 2025-06-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_org'),
        ('issue_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='issueimage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
