# Generated by Django 5.2 on 2025-09-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('issue_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.space'),
        ),
    ]
