# Generated by Django 5.2 on 2025-06-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0002_issue_organisation_issue_slug_issueimage_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='organisation',
            new_name='org',
        ),
    ]
