# Generated by Django 5.2 on 2025-09-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0003_alter_issue_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='issueimage',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
