# Generated by Django 5.2 on 2025-09-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0004_alter_issue_slug_alter_issuecomment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='issueimage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
