# Generated by Django 5.2 on 2025-07-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0005_issue_maintainer'),
        ('service_management', '0013_remove_spacesettings_enable_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='space',
            field=models.ForeignKey(blank=True, help_text='Space where this issue was reported', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='service_management.spaces'),
        ),
    ]
