# Generated by Django 5.2 on 2025-09-19 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0005_alter_issue_slug_alter_issuecomment_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tasks', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tasks', to='issue_management.issue')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTaskShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('recipient_email', models.EmailField(blank=True, help_text='Email of external recipient (optional)', max_length=254, null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='Name of external recipient (optional)', max_length=100, null=True)),
                ('permission_level', models.CharField(choices=[('view_only', 'View Only'), ('comment', 'View and Comment'), ('collaborate', 'View, Comment, and Update Status')], default='view_only', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this share link expires')),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('max_access_count', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this link can be accessed', null=True)),
                ('allow_download_attachments', models.BooleanField(default=True)),
                ('password_protected', models.BooleanField(default=False)),
                ('access_password', models.CharField(blank=True, help_text='Optional password for additional security', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this share', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_task_shares', to=settings.AUTH_USER_MODEL)),
                ('work_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='issue_management.worktask')),
            ],
            options={
                'verbose_name': 'Work Task Share',
                'verbose_name_plural': 'Work Task Shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
