# Generated by Django 5.2 on 2025-07-23 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0007_alter_issue_options_issue_due_date_issue_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='Maintainer who escalated the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Reason for escalating the issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuestatushistory',
            name='new_status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issuestatushistory',
            name='old_status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
