# Generated by Django 5.2 on 2025-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0007_add_user_to_issuecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notes describing how the issue was resolved', null=True),
        ),
    ]
