# Generated by Django 5.2 on 2025-09-25 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0008_issue_resolution_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the issue was assigned', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Who assigned this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Supervisor assigned to handle this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='requires_review',
            field=models.BooleanField(default=False, help_text='Whether this issue requires review before being marked as resolved'),
        ),
        migrations.AddField(
            model_name='issue',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from the review process', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the issue was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Who reviewed this issue (if review required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
