# Generated by Django 5.2 on 2025-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0008_issue_escalated_at_issue_escalated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='escalation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this issue has been escalated'),
        ),
    ]
