# Generated by Django 5.2 on 2025-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0009_issue_assigned_at_issue_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='worktask',
            options={'ordering': ['completed', 'due_date']},
        ),
    ]
