# Generated by Django 5.2 on 2025-07-24 05:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0009_issue_escalation_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_work_time', models.DurationField(blank=True, help_text='Total time worked excluding breaks', null=True)),
                ('total_break_time', models.DurationField(default=datetime.timedelta, help_text='Total time spent on breaks')),
                ('session_notes', models.TextField(blank=True, help_text='Notes about work done in this session')),
                ('is_focus_mode', models.BooleanField(default=False, help_text='Whether this session was in focus mode')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='issue_management.issue')),
                ('maintainer', models.ForeignKey(limit_choices_to={'profile__user_type': 'maintainer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Issue Work Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueBreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('break_type', models.CharField(choices=[('short', 'Short Break (5-15 min)'), ('medium', 'Medium Break (15-30 min)'), ('long', 'Long Break (30+ min)'), ('manual', 'Manual Break')], default='manual', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='issue_management.issueworksession')),
            ],
            options={
                'verbose_name_plural': 'Issue Break Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
