# Generated by Django 5.2 on 2025-10-14 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0010_alter_issue_options_alter_worktask_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to review this issue when requires_review is checked', related_name='issues_to_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
