# Generated by Django 5.2 on 2025-07-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0010_issueworksession_issuebreaksession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='image',
            field=models.ImageField(upload_to='public/issue_images/'),
        ),
    ]
