# Generated by Django 5.2 on 2025-10-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0011_issue_reviewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTaskResolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/work_task_resolution_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('work_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_images', to='issue_management.worktask')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
