# Generated by Django 5.2 on 2025-08-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0011_alter_issueimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='public/issue_voices/'),
        ),
    ]
