# Generated by Django 5.2 on 2025-08-24 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0012_alter_issue_voice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueResolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/issue_resolution_images/')),
                ('description', models.CharField(blank=True, help_text='Optional description of the resolution image', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_images', to='issue_management.issue')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'profile__user_type': 'maintainer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Resolution Image',
                'verbose_name_plural': 'Issue Resolution Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
