# Generated by Django 5.2 on 2025-10-16 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0013_issueresolutionimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of the site visit purpose', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what needs to be done during the visit')),
                ('scheduled_date', models.DateTimeField(help_text='When the site visit is scheduled')),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated duration of the site visit', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the visit actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the visit was completed', null=True)),
                ('findings', models.TextField(blank=True, help_text='Findings and observations from the site visit', null=True)),
                ('actions_taken', models.TextField(blank=True, help_text='Actions taken during the site visit', null=True)),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for follow-up actions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('assigned_to', models.ForeignKey(help_text='Maintainer or supervisor assigned to perform the visit', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_site_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Supervisor who created this site visit', on_delete=django.db.models.deletion.CASCADE, related_name='created_site_visits', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='issue_management.issue')),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/site_visit_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='issue_management.sitevisit')),
            ],
            options={
                'verbose_name': 'Site Visit Image',
                'verbose_name_plural': 'Site Visit Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
