# Generated by Django 5.2 on 2025-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0014_sitevisit_sitevisitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='location',
            field=models.CharField(default='Location to be specified', help_text='Location/address where the site visit will take place', max_length=300),
        ),
    ]
