# Generated by Django 5.2 on 2025-10-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0015_sitevisit_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Review comment or feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='issue_management.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_review_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Review Comment',
                'verbose_name_plural': 'Issue Review Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueReviewCommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/review_comment_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('review_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='issue_management.issuereviewcomment')),
            ],
            options={
                'verbose_name': 'Review Comment Image',
                'verbose_name_plural': 'Review Comment Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
