# Generated by Django 5.2 on 2025-10-18 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0016_issuereviewcomment_issuereviewcommentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Issue Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Issue Assigned'), ('reassigned', 'Issue Reassigned'), ('unassigned', 'Issue Unassigned'), ('updated', 'Issue Updated'), ('resolved', 'Issue Resolved'), ('reopened', 'Issue Reopened'), ('closed', 'Issue Closed'), ('cancelled', 'Issue Cancelled'), ('escalated', 'Issue Escalated'), ('review_requested', 'Review Requested'), ('reviewed', 'Issue Reviewed'), ('work_task_created', 'Work Task Created'), ('work_task_updated', 'Work Task Updated'), ('work_task_completed', 'Work Task Completed'), ('work_task_reopened', 'Work Task Reopened'), ('work_task_deleted', 'Work Task Deleted'), ('site_visit_created', 'Site Visit Created'), ('site_visit_updated', 'Site Visit Updated'), ('site_visit_completed', 'Site Visit Completed'), ('site_visit_cancelled', 'Site Visit Cancelled'), ('image_added', 'Image Added'), ('image_deleted', 'Image Deleted'), ('voice_added', 'Voice Recording Added'), ('voice_deleted', 'Voice Recording Deleted')], max_length=30)),
                ('description', models.TextField(help_text='Detailed description of what changed')),
                ('old_value', models.TextField(blank=True, help_text='Previous value (if applicable)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='issue_management.issue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Activity',
                'verbose_name_plural': 'Issue Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue', '-created_at'], name='issue_manag_issue_i_fef94c_idx')],
            },
        ),
    ]
