# Generated by Django 5.2 on 2026-01-19 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_fcm_token'),
        ('issue_management', '0017_issueactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of what needs to be purchased', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the purchase request')),
                ('estimated_amount', models.DecimalField(decimal_places=2, help_text='Estimated cost in currency', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from central admin when approving/rejecting', null=True)),
                ('slug', models.SlugField(unique=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='issue_management.issue')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='core.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='core.space')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['issue', '-requested_at'], name='issue_manag_issue_i_2ee8b3_idx'), models.Index(fields=['status', '-requested_at'], name='issue_manag_status_7c1612_idx')],
            },
        ),
    ]
