# Generated by Django 5.2 on 2026-01-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0018_purchaserequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='description',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='item',
            field=models.CharField(default='Item to be specified', help_text='Name/description of the item to purchase', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units needed'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost in currency (optional)', max_digits=10, null=True),
        ),
    ]
