# Generated by Django 5.2 on 2026-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0019_remove_purchaserequest_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='title',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes or details about the purchase request', null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='item',
            field=models.CharField(help_text='Name/description of the item to purchase', max_length=300),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of units needed'),
        ),
    ]
