# Generated by Django 5.2 on 2026-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0020_remove_purchaserequest_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Issue Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Issue Assigned'), ('reassigned', 'Issue Reassigned'), ('unassigned', 'Issue Unassigned'), ('updated', 'Issue Updated'), ('resolved', 'Issue Resolved'), ('reopened', 'Issue Reopened'), ('closed', 'Issue Closed'), ('cancelled', 'Issue Cancelled'), ('escalated', 'Issue Escalated'), ('review_requested', 'Review Requested'), ('reviewed', 'Issue Reviewed'), ('work_task_created', 'Work Task Created'), ('work_task_updated', 'Work Task Updated'), ('work_task_completed', 'Work Task Completed'), ('work_task_reopened', 'Work Task Reopened'), ('work_task_deleted', 'Work Task Deleted'), ('site_visit_created', 'Site Visit Created'), ('site_visit_updated', 'Site Visit Updated'), ('site_visit_completed', 'Site Visit Completed'), ('site_visit_cancelled', 'Site Visit Cancelled'), ('purchase_request_created', 'Purchase Request Created'), ('purchase_request_approved', 'Purchase Request Approved'), ('purchase_request_rejected', 'Purchase Request Rejected'), ('purchase_request_deleted', 'Purchase Request Deleted'), ('image_added', 'Image Added'), ('image_deleted', 'Image Deleted'), ('voice_added', 'Voice Recording Added'), ('voice_deleted', 'Voice Recording Deleted')], max_length=30),
        ),
    ]
