# Generated by Django 5.2 on 2026-01-21 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_fcm_token'),
        ('issue_management', '0021_alter_issueactivity_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/name for this shopping list', max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated amount for all items', max_digits=12, null=True)),
                ('item_count', models.PositiveIntegerField(default=0, help_text='Total number of purchase requests in this list')),
                ('slug', models.SlugField(unique=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='core.organization')),
            ],
            options={
                'verbose_name': 'Shopping List',
                'verbose_name_plural': 'Shopping Lists',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_snapshot', models.CharField(help_text='Item name at time of list generation', max_length=300)),
                ('quantity_snapshot', models.PositiveIntegerField(help_text='Quantity at time of list generation')),
                ('amount_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Amount at time of list generation', max_digits=10, null=True)),
                ('space_name', models.CharField(help_text='Space name at time of list generation', max_length=200)),
                ('issue_title', models.CharField(help_text='Issue title at time of list generation', max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='issue_management.purchaserequest')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='issue_management.shoppinglist')),
            ],
            options={
                'verbose_name': 'Shopping List Item',
                'verbose_name_plural': 'Shopping List Items',
                'ordering': ['space_name', 'item_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['org', '-generated_at'], name='issue_manag_org_id_cdebee_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'space_name'], name='issue_manag_shoppin_b52382_idx'),
        ),
    ]
