# Generated by Django 5.2 on 2026-01-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0022_shoppinglist_shoppinglistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the issue', max_length=20, null=True, unique=True),
        ),
    ]
