# Generated by Django 5.2 on 2025-09-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization association (optional for superusers, required for all other users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization'),
        ),
    ]
