# Generated by Django 5.2 on 2025-06-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_org'),
        ('service_management', '0002_workcategory_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skilled_users', to='service_management.workcategory'),
        ),
    ]
