# Generated by Django 5.2 on 2025-09-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
