# Generated by Django 5.2 on 2025-07-14 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('central_admin', 'Central Admin'), ('institution_admin', 'Insitution Admin'), ('departement_incharge', 'Departement Incharge'), ('room_incharge', 'Room Incharge'), ('space_admin', 'Space Admin'), ('maintainer', 'Maintainer'), ('general_user', 'General User')], default='general_user', max_length=20),
        ),
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_access_enabled', models.BooleanField(default=True, help_text='Enable/disable access to this space')),
                ('allow_public_access', models.BooleanField(default=False, help_text='Allow public access without authentication')),
                ('require_approval', models.BooleanField(default=False, help_text='Require admin approval for new users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='core.organisation')),
                ('space_admins', models.ManyToManyField(blank=True, help_text='Users who can administer this space', limit_choices_to={'profile__user_type': 'space_admin'}, related_name='administered_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'unique_together': {('name', 'organisation')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_active_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_active_users', to='core.spaces'),
        ),
    ]
