# Generated by Django 5.2 on 2025-07-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_user_type_spaces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaces',
            name='allow_public_access',
        ),
        migrations.AlterField(
            model_name='spaces',
            name='require_approval',
            field=models.BooleanField(default=False, help_text='Require admin approval for new space admins'),
        ),
        migrations.CreateModel(
            name='SpaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_issue_management', models.BooleanField(default=True, help_text='Enable/disable issue management module')),
                ('enable_service_management', models.BooleanField(default=True, help_text='Enable/disable service management module')),
                ('enable_transportation', models.BooleanField(default=False, help_text='Enable/disable transportation module')),
                ('enable_dashboard', models.BooleanField(default=True, help_text='Enable/disable dashboard module')),
                ('require_issue_approval', models.BooleanField(default=False, help_text='Require admin approval for new issues')),
                ('enable_issue_comments', models.BooleanField(default=True, help_text='Enable comments on issues')),
                ('enable_issue_attachments', models.BooleanField(default=True, help_text='Allow file attachments on issues')),
                ('enable_service_requests', models.BooleanField(default=True, help_text='Enable service request functionality')),
                ('enable_service_purchases', models.BooleanField(default=False, help_text='Enable service purchase functionality')),
                ('enable_service_upgrades', models.BooleanField(default=False, help_text='Enable service upgrade functionality')),
                ('auto_assign_maintainers', models.BooleanField(default=False, help_text='Automatically assign maintainers to services')),
                ('enable_transport_booking', models.BooleanField(default=False, help_text='Enable transportation booking')),
                ('require_transport_approval', models.BooleanField(default=True, help_text='Require approval for transport bookings')),
                ('max_advance_booking_days', models.PositiveIntegerField(default=30, help_text='Maximum days in advance for booking')),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('in_app_notifications', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.spaces')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_space_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Space Settings',
                'verbose_name_plural': 'Space Settings',
            },
        ),
    ]
