# Generated by Django 5.2 on 2025-07-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_spaces_allow_public_access_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spaces',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='spaces',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='spaces',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='spaces',
            name='space_admins',
        ),
    ]
