# Generated by Django 5.2 on 2025-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_organization_slug_alter_space_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='label',
            field=models.CharField(blank=True, help_text='Optional short label for the space', max_length=100, null=True),
        ),
    ]
