# Generated by Django 5.2 on 2025-07-15 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_spaces_unique_together_and_more'),
        ('service_management', '0009_spaces_spacesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_active_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_active_users', to='service_management.spaces'),
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='space',
        ),
        migrations.RemoveField(
            model_name='spacesettings',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Spaces',
        ),
        migrations.DeleteModel(
            name='SpaceSettings',
        ),
    ]
