# Generated by Django 5.2 on 2025-10-01 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_space_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_space',
            field=models.ForeignKey(blank=True, help_text='Currently active space for space admins (used for context switching)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.space'),
        ),
    ]
