# Generated by Django 5.2 on 2025-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_current_active_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='currency_code',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)')], default='INR', max_length=3),
        ),
    ]
