# Generated by Django 5.2 on 2025-08-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_maintainer_space_assignments'),
        ('core', '0008_organisation_currency_code'),
    ]

    operations = [
    ]
