# Generated by Django 5.2 on 2025-10-04 13:40

from django.db import migrations


def add_phone_numbers_to_users(apps, schema_editor):
    """
    Add phone numbers to users that don't have one.
    This is a data migration to prepare for making phone_number required.
    """
    User = apps.get_model('core', 'User')
    
    # Get all users without phone numbers
    users_without_phone = User.objects.filter(phone_number__isnull=True)
    
    # Counter for generating unique phone numbers
    counter = 1000
    
    for user in users_without_phone:
        # Generate a temporary unique phone number
        # Format: +9999999XXXX where XXXX is the counter
        temp_phone = f"+9999999{counter:04d}"
        
        # Make sure it's unique
        while User.objects.filter(phone_number=temp_phone).exists():
            counter += 1
            temp_phone = f"+9999999{counter:04d}"
        
        # Assign the phone number
        user.phone_number = temp_phone
        user.save()
        
        print(f"Assigned temp phone {temp_phone} to user {user.email or user.id}")
        counter += 1


def reverse_phone_numbers(apps, schema_editor):
    """
    Reverse the data migration by removing temporary phone numbers.
    """
    User = apps.get_model('core', 'User')
    
    # Remove phone numbers that start with +9999999 (temporary ones)
    User.objects.filter(phone_number__startswith='+9999999').update(phone_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_active_space'),
    ]

    operations = [
        migrations.RunPython(add_phone_numbers_to_users, reverse_phone_numbers),
    ]
