# Generated by Django 5.2 on 2025-08-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250804_1840'),
        ('service_management', '0013_remove_spacesettings_enable_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_spaces',
            field=models.ManyToManyField(blank=True, help_text='Spaces this maintainer is assigned to. Leave empty for organization-wide availability.', related_name='assigned_maintainers', to='service_management.spaces'),
        ),
    ]
