# Generated by Django 5.2 on 2025-10-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_make_phone_number_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, help_text='Hashed 4-digit PIN for quick authentication (not available for general users and superusers)', max_length=128, null=True),
        ),
    ]
