# Generated by Django 5.2 on 2026-02-02 05:30

from django.db import migrations, models
from django.utils.text import slugify
import random
import string


def generate_unique_slug_for_migration(apps, base_slug, model_class):
    """Generate a unique slug by appending random characters if needed"""
    slug = base_slug[:46]  # Leave room for 4-char suffix
    original_slug = slug
    counter = 0
    
    while model_class.objects.filter(slug=slug).exists():
        # Generate 4 random alphanumeric characters
        random_suffix = ''.join(random.choices(string.ascii_lowercase + string.digits, k=4))
        slug = f"{original_slug}-{random_suffix}"
        counter += 1
        if counter > 100:  # Safety limit
            slug = f"{original_slug}-{random.randint(1000, 9999)}"
            break
    
    return slug


def generate_slugs_for_existing_users(apps, schema_editor):
    """Generate slugs for existing users"""
    User = apps.get_model('core', 'User')
    
    for user in User.objects.all():
        if not user.slug:
            # Use email or phone number as base for slug
            if user.email:
                base_slug = slugify(user.email.split('@')[0])
            elif user.phone_number:
                base_slug = slugify(user.phone_number.replace('+', '').replace('-', ''))
            else:
                base_slug = f"user-{user.id}"
            
            user.slug = generate_unique_slug_for_migration(apps, base_slug, User)
            user.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(generate_slugs_for_existing_users, reverse_code=migrations.RunPython.noop),
    ]
