# Generated by Django 5.2 on 2025-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='issue_images/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='issue_voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
