# Generated by Django 5.2 on 2025-06-09 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporthub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='issue_images/')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reporthub.issue')),
            ],
        ),
    ]
